### PR TITLE
Improve behaviour when database is locked: try to retrieve credential…

### PR DESCRIPTION
**Pull request by LEDfan**
…s again for some time

When using the option to automatically lock the Keepass database when you lock your computer you'll have to ask Keywi to fill the credentials two times (and there was a bug in it too when using the context menu):
after

With this PR Keywi will retry to retrieve the credentials 20 times, with a 500ms delay between two tries:
before

For this I had to convert the `Keepass.getLogins` and `Keepass.associate` methods to uses promises instead of callbacks, which was on our TODO list anyway.

@RobinJadoul please give this a good test, it changes some important code.

I'll release a beta when this is merged.

### CODE REVIEW

**Comment by RobinJadoul** [comment]
I haven't recently encountered this as being a problem because I have this option enabled for KeepassHTTP
Unlock at keepasshttp request
If this isn't generally available in other keepass versions, we might go with this, but I'd still like a notification that it failed, because right now, it may seem as Keywi just not working or being slow

**Comment by RobinJadoul** [comment]
What exactly was the bug in the context menu?

**Comment by LEDfan** [comment]
> I haven't recently encountered this as being a problem because I have this option enabled for KeepassHTTP

Using Keepass(.info) it's working as expected, unfortunately KeepassXC works a bit different. Let's first try to fix it there before merging this: https://github.com/keepassxreboot/keepassxc/blob/a4d1293eaf20555fef326c496694947dfaab9bb3/src/http/Service.cpp#L120

> What exactly was the bug in the context menu?

See #100

**Comment by LEDfan** [comment]
Everything useful has been moved to other PR's/commits.

Since Keepassxc has implemented some new protocol, we should have a more global discussion on the path forward. I'll close this in the mean time.

**Pull request closed without merging**
