### PR TITLE
Fix spacing issue on windows

### PR DESCRIPTION
**Pull request by LEDfan**
On windows the window border is included in the Height and Width of a
window.

afbeelding

I though fixing the underlying issue was better than trying to find optimal CSS values.

### CODE REVIEW

**Comment by RobinJadoul** [comment]
It still seems strange that firefox would behave so differently. Could we find this documented somewhere, just to confirm?
It feels hacky to do a hardcoded check for windows (and for example what about OS X)

**Comment by LEDfan** [comment]
According to the documentation:
> (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/create)
> integer. The height in pixels of the new window, including the frame. If not specified defaults to a natural height.

The fun starts because we use the same GTK theme, so it's realistic that other GTK themes will cause the same issue.

**Comment by RobinJadoul** [comment]
So, we should find an other solution.
Maybe something not relying on absolute CSS values?

**Comment by LEDfan** [comment]
Sounds good, maybe we can try to let the footer fill up all space that is left? This way it doesn't look 100% the same on all platforms, but at least the forms are always visible.

**Comment by RobinJadoul** [comment]
That might solve the issue

**Pull request closed without merging**
